### ISSUE TITLE
SD+WiFi image device-tree error 

### ISSUE THREAD

**Issue by QB4-dev** [joelguittet/meta-somlabs-examples#1]
https://github.com/myfreescalewebpage/meta-somlabs-examples/blob/cda402c3f0c22c3c9ecbaac39c937557278e567e/meta-somlabs-example-visioncb-6ull-std/recipes-kernel/linux/files/sls16y2_792c_512r_sd_1wb.dts#L10

should be `#include "sls16xx-sd.dtsi"`

**Comment by myfreescalewebpage** [comment]
@QB4-dev just seen your issue, fixed with https://github.com/myfreescalewebpage/meta-somlabs-examples/commit/4eeb6a7050965ef5a813a56955fc0e20846f725b.
